# Generated by Django 4.2.3 on 2023-08-03 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lodgingMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('homePageURL', models.CharField(max_length=50)),
                ('headCount', models.IntegerField()),
                ('scrap', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('precaution', models.TextField()),
                ('check_in_time', models.CharField(max_length=20)),
                ('check_out_time', models.CharField(max_length=20)),
                ('mainPhoto', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='lodgingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.ImageField(null=True, upload_to='review/')),
                ('contents', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='lodgingScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap', models.BooleanField(default=False)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodgingmain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lodgingmain',
            name='photos',
            field=models.ManyToManyField(to='lodging.lodgingphoto'),
        ),
    ]
