# Generated by Django 4.2.3 on 2023-08-05 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lodging.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lodgingMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('homePageURL', models.CharField(max_length=50)),
                ('headCount', models.IntegerField()),
                ('scrap', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('precaution', models.TextField()),
                ('checkInTime', models.CharField(max_length=20)),
                ('checkOutTime', models.CharField(max_length=20)),
                ('mainPhoto', models.ImageField(blank=True, null=True, upload_to=lodging.models.lodging_main_photo_path)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review/')),
                ('contents', models.TextField(null=True)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodgingmain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='priceByDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodgingmain')),
            ],
        ),
        migrations.CreateModel(
            name='lodgingScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isScrap', models.BooleanField(default=False)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodgingmain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='lodgingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lodging.models.lodging_sub_photos_path)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lodging.lodgingmain')),
            ],
        ),
    ]
