# Generated by Django 4.2.3 on 2023-08-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodgingmain',
            old_name='check_in_time',
            new_name='checkInTime',
        ),
        migrations.RenameField(
            model_name='lodgingmain',
            old_name='check_out_time',
            new_name='checkOutTime',
        ),
    ]
