# Generated by Django 4.2.3 on 2023-08-04 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recreation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recreationMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=recreation.models.recreation_main_photo_path)),
                ('headCountMin', models.IntegerField()),
                ('headCountMax', models.IntegerField()),
                ('scrap', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='recreationScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap', models.BooleanField(default=False)),
                ('recreation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recreationScrap', to='recreation.recreationmain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
